### ISSUE TITLE
Symfony 4

### ISSUE THREAD

**Issue by jackbentley** [vivait/StringGeneratorBundle#36]
Not compatible with Symfony 4

**Comment by kieljohn** [comment]
Hi Jack, thanks for the report, we typically follow the LTS branches of Symfony so migration of dependant bundles isn't scheduled until we migrate to SF4.4. Would appreciate a PR if it's an issue for you however.

**Comment by tattali** [comment]
Hi any updates ?

**Comment by kieljohn** [comment]
Sorry, no. As I mentioned in the previous message, SF4 isn't on our internal radar until release of the LTS branch 4.4. We will prioritise a review on any PR's to it though.

**Comment by terox** [comment]
@tattali @kieljohn the #39 could help, I think

**Comment by Brunty** [comment]
@terox tagged a new release here from your PR: https://github.com/vivait/StringGeneratorBundle/releases/tag/4.0.0

Thanks for the work! 👍
